// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Русский — translated and hand-checked, not machine output.
extension Strings {
    static let ru = Strings(
        statusIdleTooltip: "Vorssaint: обычный сон",
        statusActiveUntil: "Vorssaint: активно до",
        statusActiveIndefinite: "Vorssaint: активно бессрочно",
        menuEnableAwake: "Включить «Не засыпать»",
        menuDisableAwake: "Выключить «Не засыпать»",
        menuActivateFor: "Включить на…",
        menuSettings: "Настройки…",
        menuAbout: "О приложении Vorssaint",
        menuQuit: "Завершить Vorssaint",
        menuHide: "Скрыть Vorssaint",
        menuHideOthers: "Скрыть остальные",
        menuShowAll: "Показать все",
        menuEdit: "Правка",
        menuUndo: "Отменить",
        menuRedo: "Повторить",
        menuCut: "Вырезать",
        menuCopy: "Скопировать",
        menuPaste: "Вставить",
        menuSelectAll: "Выбрать все",
        menuWindow: "Окно",
        menuMinimize: "Свернуть",
        menuZoom: "Масштаб",
        menuClose: "Закрыть",

        minutes15: "15 минут",
        minutes30: "30 минут",
        hour1: "1 час",
        hours2: "2 часа",
        hours4: "4 часа",
        hours8: "8 часов",
        indefinitely: "Бессрочно",
        indefinite: "Бессрочно",

        panelAwake: "Mac не спит",
        panelNormalSleep: "Обычный сон",
        panelSettings: "Настройки",
        panelQuit: "Выйти",
        panelHotkeyHint: "Сочетание переключает",

        keepAwakeTitle: "Не засыпать",
        keepAwakeEndsIn: "Завершится через",
        keepAwakeUntilDisabled: "Активно, пока не выключите",
        keepAwakeNormalRules: "Mac следует обычным правилам энергосбережения",
        keepAwakeOptions: "Параметры",
        keepAwakeMouseJiggle: "Слегка двигать курсор",
        keepAwakeMouseJiggleCaption: "Во время сеанса немного двигает курсор с выбранным интервалом.",
        keepAwakeMouseJiggleInterval: "Интервал",
        keepAwakeIconTintLabel: "Цвет активного значка",
        keepAwakeIconTintOrange: "Оранжевый",
        keepAwakeIconTintGreen: "Зелёный",
        keepAwakeIconTintBlue: "Синий",
        keepAwakeIconTintPurple: "Фиолетовый",
        keepAwakeIconTintPink: "Розовый",
        keepAwakeIconTintNone: "Без цвета",
        durationLabel: "Длительность",
        clamshellTitle: "Работать с закрытой крышкой",
        clamshellOnCaption: "Сон полностью отключён. Следите за питанием",
        clamshellNeedsSession: "Применяется, когда активно «Не засыпать»",
        clamshellReady: "Готово. Переключается без пароля",
        clamshellNeedsPassword: "Один раз запросит пароль администратора",

        systemSection: "Система",
        temperatures: "Температуры",
        cpuLabel: "ЦП",
        gpuLabel: "ГП",
        batteryLabel: "Батарея",
        usageSection: "Загрузка оборудования",
        memorySection: "Память",
        memoryPressure: "Нагрузка",
        pressureNormal: "Норма",
        pressureWarning: "Внимание",
        pressureCritical: "Критическая",
        monitorUnavailable: "Датчики недоступны на этом Mac",
        energyAppsTitle: "Приложения, активно тратящие энергию",
        energyAppsIdle: "Нет заметного расхода энергии",

        notifySessionEndedTitle: "Сеанс завершён",
        notifySessionEndedBody: "Время вышло. Mac снова будет засыпать как обычно.",
        notifyBatteryTitle: "Vorssaint отключён",
        notifyBatteryBody: "Низкий заряд. Обычный сон восстановлен, чтобы сберечь батарею.",
        adminPromptClamshellOn: "Vorssaint нужен ваш пароль, чтобы Mac продолжал работать с закрытой крышкой.",
        adminPromptClamshellOff: "Vorssaint нужен ваш пароль, чтобы восстановить обычный сон Mac.",
        adminPromptRecover: "Vorssaint завершился, пока сон Mac был отключён. Введите пароль, чтобы восстановить обычный сон.",
        adminPromptSudoersInstall: "Vorssaint создаст ограниченное правило (только pmset disablesleep), чтобы переключать режим закрытой крышки без запроса пароля. Пароль понадобится только сейчас.",
        adminPromptSudoersRemove: "Vorssaint удалит правило закрытой крышки без пароля.",

        settingsTitle: "Настройки Vorssaint",
        tabGeneral: "Основные",
        tabEnergy: "Энергия",
        tabMouse: "Мышь",
        tabSwitcher: "Переключатель",
        tabAdvanced: "Дополнительно",
        tabAbout: "О программе",
        tabReleaseNotes: "Что нового",
        releaseNotesOnUpdateToggle: "Показывать новости после обновления",
        whatsNewDontShowAgain: "Больше не показывать",
        previewSizeLabel: "Размер превью",
        previewSizeNormal: "Обычный",
        previewSizeLarge: "Большой",
        previewSizeXLarge: "Очень большой",
        settingsGroupFeatures: "Функции",
        advancedResetSection: "Разрешения",
        advancedResetDescription: "Удаляет все разрешения, выданные Vorssaint (Универсальный доступ, Запись экрана, Полный доступ к диску и другие), элемент автозапуска и правило закрытой крышки. Полезно, чтобы начать с чистого листа или перед удалением. Приложение остаётся установленным.",
        advancedClearButton: "Сбросить все разрешения",
        advancedCleared: "Разрешения сброшены.",
        advancedClearConfirmTitle: "Сбросить все разрешения?",
        advancedClearConfirmBody: "Функции, которым нужны разрешения, перестанут работать, пока вы не выдадите их снова. Ваши настройки сохранятся.",
        advancedUninstallSection: "Удаление",
        advancedUninstallDescription: "Делает всё перечисленное выше, затем удаляет настройки и перемещает Vorssaint в Корзину, не оставляя следов. По завершении приложение закроется. Переустановить можно в любой момент.",
        advancedUninstallButton: "Полностью удалить Vorssaint",
        advancedUninstallConfirmTitle: "Удалить Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint сбросит разрешения, удалит настройки и переместится в Корзину, затем закроется. Из приложения это не отменить, но он останется в Корзине, пока вы её не очистите.",

        launchAtLogin: "Запускать при входе",
        languageLabel: "Язык",
        menuBarSection: "Строка меню",
        showCountdown: "Показывать оставшееся время рядом со значком",
        globalHotkeySection: "Глобальное сочетание",
        hotkeyToggle: "Включить сочетание для «Не засыпать»",
        hotkeyCaption: "Работает в любом приложении, без дополнительных разрешений.",

        sessionSection: "Сеанс",
        defaultDurationLabel: "Длительность по умолчанию",
        keepAwakeAutoStart: "Включать при запуске приложения",
        keepAwakeAutoStartCaption: "Автоматически запускает «Не засыпать».",
        batteryProtectionSection: "Защита батареи",
        batteryDisableBelow: "Отключать при заряде ниже",
        batteryNever: "Никогда",
        batteryProtectionCaption: "Не даёт забытому сеансу разрядить батарею MacBook.",
        clamshellSection: "Закрытая крышка",
        configuring: "Настройка…",
        sudoersFailed: "Не удалось включить режим закрытой крышки. Попробуйте снова.",
        clamshellExplanation: "«Работать с закрытой крышкой» полностью отключает сон, пока активно «Не засыпать», и автоматически возвращается обратно по завершении сеанса или закрытии приложения. Лучше использовать при подключённом питании.",

        scrollSection: "Прокрутка",
        invertMouseScroll: "Инвертировать прокрутку мыши",
        invertMouseScrollCaption: "Меняет направление колеса мыши на противоположное.",
        scrollTrackpadNote: "Трекпад не меняется: остаётся естественная прокрутка macOS.",
        scrollActiveNow: "Прокрутка мыши сейчас инвертируется",

        switcherSection: "Переключатель приложений",
        switcherEnable: "Использовать переключатель Vorssaint",
        switcherEnableCaption: "Переключайте окна по реальным миниатюрам, в том числе между несколькими окнами одного приложения.",
        switcherUsageHint: "Удерживайте сочетание для навигации; отпустите, чтобы активировать окно. Shift или ← — назад; Q закрывает выбранное приложение; Esc отменяет.",
        switcherNoWindows: "Нет открытых окон",
        switcherMergeTabs: "Показывать одну запись на приложение",
        switcherMergeTabsCaption: "Объединяет все окна приложения в одну запись переключателя вместо отдельной записи на каждое окно.",
        switcherShowFinder: "Показывать Finder без окон",
        switcherShowFinderCaption: "Показывает Finder в переключателе, даже когда ни одно окно Finder не открыто.",
        dockPreviewName: "Превью из Dock",
        dockPreviewEnable: "Превью окон из Dock",
        dockPreviewEnableCaption: "Наведите курсор на открытое приложение в Dock, чтобы увидеть и просмотреть его окна.",
        dockPreviewActiveNow: "Активно в Dock",
        dockPreviewMagnificationBlocked: "Отключите увеличение Dock, чтобы использовать это.",
        dockPreviewDockUnavailable: "Не удалось прочитать элементы Dock.",
        dockPreviewAutohideBeta: "Бета. Возможны ошибки.",
        dockPreviewCloseWindow: "Закрыть окно",
        dockPreviewIntroPeek: "Наведите курсор на миниатюру для просмотра. Нажмите, чтобы открыть окно.",
        dockPreviewIntroSettingsHint: "Это можно изменить позже в «Настройки › Переключатель».",
        dockPreviewIntroLater: "Не сейчас",
        dockPreviewIntroEnable: "Включить превью из Dock",
        dockPreviewIntroMagnificationAction: "Отключите увеличение Dock, чтобы включить.",

        cutPasteName: "Вырезать и вставить",
        cutPasteEnable: "Вырезать и вставлять файлы в Finder",
        cutPasteEnableCaption: "Используйте ⌘X, чтобы вырезать, и ⌘V, чтобы перемещать файлы и папки в Finder.",
        cutPasteHowTitle: "Как пользоваться",
        cutPasteStep1: "Выберите элементы в Finder и нажмите ⌘X, чтобы вырезать их.",
        cutPasteStep2: "Откройте папку назначения и нажмите ⌘V, чтобы переместить их туда.",
        cutPasteTextNote: "В текстовых полях (например, при переименовании) ⌘X и ⌘V работают как обычно.",
        cutPasteActiveNow: "Готово к вырезанию в Finder",
        cutPasteAutomationNote: "В первый раз macOS запросит разрешение на управление Finder.",
        cutReadyTitle: "Вырезано",
        cutReadyHint: "в папке назначения, чтобы переместить",
        cutCancel: "Отменить вырезание",
        cutDoneTitle: "Перемещено!",
        cutMovedSingular: "1 элемент перемещён",
        cutMovedPluralFormat: "перемещено элементов: %d",
        cutSomeFailed: "Некоторые элементы не удалось переместить",

        autoQuitName: "Выход при закрытии",
        autoQuitEnable: "Завершать приложение при закрытии последнего окна",
        autoQuitEnableCaption: "Закрытие последнего окна приложения также завершает его.",
        autoQuitActiveNow: "Активно и следит за окнами",
        autoQuitHowTitle: "Как это работает",
        autoQuitStep1: "Закройте последнее окно приложения (⌘W или красная кнопка).",
        autoQuitStep2: "Приложение завершится само. Диалоги «Сохранить изменения?» по-прежнему появляются.",
        autoQuitPredictableNote: "Приложения, которые обычно работают без окна, никогда не завершаются.",
        autoQuitExceptionsTitle: "Исключения",
        autoQuitExceptionsCaption: "Приложения из этого списка остаются открытыми даже без окон.",
        autoQuitExceptionsEmpty: "Нет исключений",
        autoQuitAddApp: "Добавить приложение…",

        uninstallerName: "Деинсталлятор",
        uninstallerEnableCaption: "Удаляет приложение вместе с кэшами, настройками, журналами и остатками, которые оно оставляет.",
        uninstallerStep1: "Перетащите приложение в «Настройки» или выберите из списка.",
        uninstallerStep2: "Просмотрите найденные файлы и сколько места они занимают.",
        uninstallerStep3: "Переместите нужное в Корзину. Ничего не удаляется безвозвратно.",
        uninstallerMenuItem: "Удалить приложение…",
        uninstallerDropTitle: "Перетащите приложение сюда",
        uninstallerDropSubtitle: "или выберите одно для анализа",
        uninstallerChoose: "Выбрать приложение…",
        uninstallerPickerTitle: "Выбрать приложение",
        uninstallerPickerSearch: "Поиск приложений",
        uninstallerPickerEmpty: "Приложения не найдены",
        uninstallerEmptyNote: "Ничего не удаляется без вашего подтверждения.",
        uninstallerFDANote: "Предоставьте Полный доступ к диску для более тщательного анализа.",
        uninstallerFDAGrant: "Предоставить доступ…",
        uninstallerFDAHint: "Включите Vorssaint в списке. Если его там нет, нажмите + и выберите Vorssaint в «Программах». Доступ применяется только после перезапуска приложения.",
        uninstallerFDARelaunch: "Перезапустить сейчас",
        uninstallerScanning: "Анализ файлов…",
        uninstallerRemoving: "Перемещение в Корзину…",
        uninstallerFoundTitle: "найдено",
        uninstallerSelectedFormat: "выбрано %d из %d",
        uninstallerRemove: "Переместить в Корзину",
        uninstallerCancel: "Отмена",
        uninstallerDoneTitle: "Готово!",
        uninstallerFreedFormat: "освобождено %@",
        uninstallerSomeFailed: "Некоторые элементы не удалось переместить в Корзину.",
        uninstallerAnother: "Удалить ещё одно",
        uninstallerCatApp: "Приложение",
        uninstallerCatSupport: "Поддержка",
        uninstallerCatCaches: "Кэши",
        uninstallerCatPreferences: "Настройки",
        uninstallerCatContainers: "Контейнеры",
        uninstallerCatLogs: "Журналы",
        uninstallerCatState: "Сохранённое состояние",
        uninstallerCatOther: "Другое",

        urlCleanerName: "Очистка URL",
        urlCleanerEnable: "Очищать скопированные URL",
        urlCleanerEnableCaption: "Удаляет параметры отслеживания из скопированных ссылок.",
        urlCleanerActiveNow: "Активно и следит за буфером обмена",
        urlCleanerManualTitle: "Очистить сейчас",
        urlCleanerInputPlaceholder: "Вставьте URL",
        urlCleanerOutputPlaceholder: "Здесь появится очищенный URL",
        urlCleanerCleanButton: "Очистить",
        urlCleanerPasteButton: "Вставить",
        urlCleanerCopyButton: "Копировать",
        urlCleanerClearButton: "Очистить поле",
        urlCleanerNoURL: "Вставьте корректный URL.",
        urlCleanerNoChange: "Нечего очищать.",
        urlCleanerCleaned: "URL очищен.",
        urlCleanerCopied: "Скопировано.",
        urlCleanerLocalNote: "Локально. Без сети.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Ищите, устанавливайте и удаляйте формулы и каски.",
        homebrewMissingTitle: "Homebrew не найден",
        homebrewMissingBody: "Vorssaint может открыть Терминал с официальным установщиком Homebrew. Терминал покажет шаги и при необходимости запросит пароль.",
        homebrewInstallHomebrew: "Установить Homebrew",
        homebrewInstallHomebrewCaption: "Когда Терминал завершит работу, вернитесь сюда и нажмите «Обновить».",
        homebrewInstallHomebrewOpened: "Установщик открыт в Терминале.",
        homebrewShellSetupTitle: "Завершить настройку Терминала",
        homebrewShellSetupBody: "Homebrew установлен, но Терминал, возможно, ещё не находит команду brew. Vorssaint может открыть Терминал с командой настройки.",
        homebrewShellSetupButton: "Настроить Терминал",
        homebrewShellSetupOpened: "Команда открыта в Терминале. Затем вернитесь сюда и нажмите «Обновить».",
        homebrewRefresh: "Обновить",
        homebrewSearchPlaceholder: "Поиск пакетов",
        homebrewKeyboardHint: "Пробел или Return закрывают панель macOS. Используйте кнопку поиска.",
        homebrewSearchButton: "Найти",
        homebrewSearchResults: "Результаты",
        homebrewInstalled: "Установленные",
        homebrewAll: "Все",
        homebrewFormulas: "Формулы",
        homebrewCasks: "Каски",
        homebrewNoPackages: "Пакеты не найдены",
        homebrewNoSelection: "Выберите установленный пакет или найдите новый.",
        homebrewDetailsTitle: "Сведения о пакете",
        homebrewInstall: "Установить",
        homebrewUninstall: "Удалить",
        homebrewOpenTerminal: "Открыть Терминал",
        homebrewCancelOperation: "Отмена",
        homebrewClearLog: "Очистить журнал",
        homebrewLogTitle: "Журнал",
        homebrewVersion: "Версия",
        homebrewDescription: "Тип",
        homebrewHomepage: "Открыть сайт",
        homebrewPopularity: "Популярность",
        homebrewPopularityFormat: "%@ установок за %@ дней",
        homebrewInstalledBadge: "Установлено",
        homebrewNotInstalledBadge: "Не установлено",
        homebrewConfirmInstallTitle: "Установить через Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew загрузит и установит %@. Также могут быть установлены зависимости.",
        homebrewConfirmUninstallTitle: "Удалить через Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew удалит %@. Файлы конфигурации могут остаться в системе.",
        homebrewTerminalFallback: "Этой операции нужен Терминал, чтобы запросить пароль администратора. Vorssaint не перехватывает пароли.",
        homebrewLoading: "Загрузка…",
        homebrewSearchEmpty: "Нет результатов",
        homebrewOperationInstallFormat: "Установка %@",
        homebrewOperationUninstallFormat: "Удаление %@",
        homebrewOperationInstalledFormat: "%@ установлен.",
        homebrewOperationUninstalledFormat: "%@ удалён.",
        homebrewOperationFailedFormat: "Не удалось завершить %@.",
        homebrewOperationCancelled: "Операция отменена.",
        homebrewOperationPreparing: "Подготовка...",
        homebrewOperationDownloading: "Загрузка файлов...",
        homebrewOperationInstalling: "Установка файлов...",
        homebrewOperationUninstalling: "Удаление файлов...",
        homebrewOperationFinalizing: "Завершение...",
        homebrewOperationRefreshing: "Обновление списка...",
        homebrewOperationTerminal: "Продолжите в Терминале.",
        homebrewOperationElapsedFormat: "прошло %@",
        homebrewOperationShowDetails: "Показать детали",
        homebrewOperationHideDetails: "Скрыть детали",
        homebrewOperationTechnicalLog: "Технические детали",
        homebrewOperationProgressUnknown: "Homebrew пока не сообщил процент выполнения.",

        mediaName: "Медиа",
        mediaEnableCaption: "Сжимайте видео и изображения, создавайте GIF и извлекайте текст локально.",
        mediaLocalNote: "Локально. Без сети.",
        mediaToolVideo: "Видео",
        mediaToolGIF: "GIF",
        mediaToolImage: "Изображение",
        mediaToolText: "Текст",
        mediaSelectFile: "Выбрать файл",
        mediaDropHint: "Перетащите файл сюда или нажмите, чтобы выбрать.",
        mediaOutput: "Результат",
        mediaOutputAutomatic: "Автоматически",
        mediaChooseOutput: "Назначение",
        mediaStartVideo: "Сжать видео",
        mediaStartGIF: "Создать GIF",
        mediaStartImage: "Сжать изображение",
        mediaStartText: "Извлечь текст",
        mediaCancel: "Отмена",
        mediaStartTime: "Начало",
        mediaEndTime: "Конец",
        mediaQuality: "Сжатие",
        mediaCompressionLow: "Низкое",
        mediaCompressionMedium: "Среднее",
        mediaCompressionHigh: "Высокое",
        mediaMaxSize: "Размер",
        mediaWidth: "Ширина",
        mediaFPS: "Кадры/с",
        mediaKeepAudio: "Сохранить звук",
        mediaCodec: "Кодек",
        mediaFormat: "Формат",
        mediaStripMetadata: "Удалить метаданные",
        mediaLoopGIF: "Зациклить GIF",
        mediaOCRMode: "Распознавание",
        mediaOCRAccurate: "Точное",
        mediaOCRFast: "Быстрое",
        mediaLanguageCorrection: "Коррекция языка",
        mediaTextOutputNote: "Извлечённый текст можно скопировать и сохранить как TXT.",
        mediaRunning: "Обработка",
        mediaCompleted: "Готово",
        mediaCancelled: "Отменено.",
        mediaOpenInFinder: "Показать",
        mediaCopyText: "Копировать текст",
        mediaRunAgain: "Запустить снова",
        mediaEmptyText: "Текст не найден.",
        mediaResultSavedFormat: "Сохранено как %@",
        mediaResultSizeFormat: "%@ → %@",
        mediaErrorNoFile: "Сначала выберите файл.",
        mediaErrorNoVideo: "В этом файле нет видеодорожки.",
        mediaErrorSameOutput: "Выберите назначение, отличное от исходного файла.",
        mediaErrorUnsupported: "Формат не поддерживается macOS.",

        shelfName: "Полка",
        shelfEnable: "Временная область для перетаскивания файлов",
        shelfEnableCaption: "Плавающее место, где можно собрать файлы, изображения и текст, а позже перетащить их куда угодно.",
        shelfHowTitle: "Как пользоваться",
        shelfStep1: "Откройте сочетанием клавиш или встряхнув мышь во время перетаскивания.",
        shelfStep2: "Перетащите на неё файлы, изображения, ссылки или текст, чтобы сохранить их.",
        shelfStep3: "Перетащите каждый элемент обратно в любое приложение, когда он понадобится.",
        shelfShakeToggle: "Открывать встряхиванием мыши при перетаскивании",
        shelfShakeCaption: "Быстро встряхните курсор, удерживая элемент, чтобы вызвать полку рядом с курсором.",
        shelfHotkeyLabel: "Сочетание",
        shelfOpenNow: "Открыть сейчас",
        shelfNoPermission: "Не требует разрешений.",
        shelfMenuItem: "Открыть полку",
        shelfTitle: "Полка",
        shelfEmpty: "Перетащите элементы сюда",
        shelfClearAll: "Очистить всё",
        shelfRemoveSelected: "Удалить выбранное",
        shelfSelectedFormat: "выбрано: %d",
        shelfHint: "Нажмите, чтобы выбрать. Перетащите наружу, чтобы использовать.",
        shelfItemImage: "Изображение",

        breakdownMeasuring: "Измерение…",

        mixerSection: "Микшер громкости",
        mixerEmpty: "Приложения с аудио появляются здесь",
        mixerUnavailable: "Доступно в macOS 14.4 и новее",
        mixerPermissionBody: "Чтобы регулировать громкость по приложениям, разрешите «Запись экрана и системного звука» в Системных настройках. Звук никогда не записывается.",
        mixerResetTooltip: "Сбросить до 100%",
        mixerOutputDefault: "По умолчанию",
        mixerOutputCurrent: "текущее",
        mixerOutputUnavailable: "Вывод недоступен",
        mixerOutputFallback: "Используется устройство по умолчанию, пока это не вернётся.",
        mixerOutputTooltip: "Выбрать вывод",
        mixerSystemOutputTitle: "Вывод",
        mixerSystemOutputNoDevices: "Устройства вывода не найдены",
        mixerSystemOutputTooltip: "Выбрать системный вывод",
        mixerSystemOutputErrorFormat: "Не удалось переключить: %@",
        mixerLowerOnHeadphonesDisconnect: "Снижать громкость при отключении наушников",
        mixerLowerOnHeadphonesDisconnectCaption: "Устанавливает громкость вывода на 0% при отключении проводных или Bluetooth-наушников.",
        soundOutputSwitcherTitle: "Переключатель вывода",
        soundOutputSwitcherEnable: "Переключать вывод сочетанием",
        soundOutputSwitcherCaption: "Выберите устройства вывода и используйте сочетание, чтобы переходить к следующему доступному.",
        soundOutputSwitcherDevices: "Устройства в цикле",
        soundOutputSwitcherNoAvailableSelection: "Выберите хотя бы одно доступное устройство вывода.",
        mixerInputTitle: "Микрофон",
        mixerInputNoDevices: "Микрофоны не найдены",
        mixerInputUnavailable: "Микрофон недоступен",
        mixerInputFallback: "Используется устройство по умолчанию, пока этот микрофон не вернётся.",
        mixerInputTooltip: "Выбрать микрофон",
        mixerInputErrorFormat: "Не удалось переключить: %@",

        updatesSection: "Обновления",
        autoCheckToggle: "Проверять обновления автоматически",
        checkNowButton: "Проверить сейчас",
        updateChecking: "Проверка…",
        updateUpToDate: "У вас последняя версия.",
        updateAvailablePrefix: "Доступно обновление:",
        updateInstallButton: "Загрузить и установить",
        updateDownloading: "Загрузка обновления…",
        updateInstalling: "Установка и перезапуск…",
        updateFailedPrefix: "Не удалось проверить:",
        updateLastChecked: "Последняя проверка:",
        updateNotifyTitle: "Обновление Vorssaint",
        menuCheckUpdates: "Проверить обновления…",

        permissionRequired: "Требуется разрешение",
        permissionAccessibility: "Универсальный доступ",
        permissionScreenRecording: "Запись экрана",
        permissionGranted: "Предоставлено",
        permissionMissing: "Не предоставлено",
        permissionOpenSettings: "Открыть Системные настройки…",
        permissionRequest: "Предоставить доступ",
        permissionRestartNote: "После выдачи macOS может попросить переоткрыть приложение.",

        aboutDescription: "Центр утилит для вашего Mac.\nЭнергия, монитор системы, прокрутка и переключатель окон — прямо в строке меню.",
        versionPrefix: "Версия",
        reviewIntro: "Показать введение",
        viewOnGitHub: "Открыть на GitHub",

        obContinue: "Продолжить",
        obBack: "Назад",
        obSkipStep: "Пропустить этот шаг",
        obStart: "Открыть Vorssaint",
        obStepWelcomeTitle: "Добро пожаловать в Vorssaint",
        obStepWelcomeBody: "Ненавязчивая утилита в строке меню, которая делает повседневный macOS удобнее.",
        obWelcomeBullet1Title: "Энергия под контролем",
        obWelcomeBullet1Body: "Держите Mac бодрым сколько угодно, даже с закрытой крышкой.",
        obWelcomeBullet2Title: "Понятная картина системы",
        obWelcomeBullet2Body: "Температуры ЦП, ГП и батареи, загрузка оборудования и нагрузка на память в реальном времени.",
        obWelcomeBullet3Title: "Мышь и окна по-вашему",
        obWelcomeBullet3Body: "Инвертированная прокрутка мыши и переключатель окон с миниатюрами.",
        obLanguageLabel: "Язык",
        obStepAccessibilityTitle: "Универсальный доступ",
        obStepAccessibilityBody: "Нужен для инвертирования прокрутки мыши и чтобы переключатель окон реагировал на клавиатуру.",
        obAccessibilityWhy: "Приложение лишь отслеживает колесо мыши и сочетание переключателя. Ничего не записывается и никуда не отправляется.",
        obStepRecordingTitle: "Запись экрана",
        obStepRecordingBody: "Позволяет переключателю показывать реальные миниатюры окон, а не только значки.",
        obRecordingWhy: "Миниатюры создаются на лету, остаются в памяти и никогда не покидают ваш Mac. Без этого переключатель всё равно работает со значками.",
        obStepMonitorTitle: "Монитор системы",
        obStepMonitorBody: "Панель показывает температуры ЦП, ГП и батареи, загрузку оборудования и нагрузку на память.",
        obMonitorNoPermission: "Разрешения не нужны. Датчики читаются прямо из системы.",
        obStepOptionalTitle: "Дополнительные функции",
        obStepOptionalBody: "Включите то, что хотите использовать сейчас. Всё можно изменить позже в Настройках.",
        obStepStatusTitle: "Проверка",
        obStepStatusBody: "Убедитесь, что всё готово для нужных вам функций.",
        obStatusRecheck: "Проверить снова",
        obStepDoneTitle: "Всё готово!",
        obStepDoneBody: "Vorssaint уже заботится о вашем Mac.",
        obDoneHint: "Ищите чёрную дыру в строке меню, в правом верхнем углу экрана.",
        obWhatsNewTitle: "Что нового в этой версии",
        obWhatsNewFallback: "Это обновление включает последние исправления и улучшения.",
        obLanguageUpdateTitle: "Теперь на вашем языке",
        obLanguageUpdateBody: "Vorssaint теперь говорит на нескольких языках. Выберите нужный; изменить его можно в любой момент в Настройках.",

        tabMonitor: "Монитор",
        monitorMenuBarSection: "В строке меню",
        monitorMenuBarCaption: "Выберите, что отображается рядом со значком в строке меню.",
        monitorCombineTemperatures: "Объединить загрузку и температуру",
        monitorCombineTemperaturesCaption: "Когда включены загрузка и температура одного элемента, показывать их одним блоком.",
        monitorSeparateMenuBarMetrics: "Разделить метрики на отдельные элементы",
        monitorSeparateMenuBarMetricsCaption: "Разделяет активные блоки в строке меню и держит загрузку и температуру вместе, когда включено объединение.",
        monitorShowCPU: "ЦП",
        monitorShowMemory: "Память",
        monitorShowNetwork: "Сеть",
        monitorShowPowerLabel: "Питание",
        monitorIntervalLabel: "Обновлять каждые",
        monitorInterval1: "1 секунда",
        monitorInterval2: "2 секунды",
        monitorInterval5: "5 секунд",
        monitorPanelSection: "В панели",
        panelNavigationMode: "Навигация по панели по разделам",
        panelNavigationCaption: "Показывает по одному разделу за раз и размещает навигацию внизу панели.",
        panelFooterSections: "Разделы",
        panelFooterList: "Список",
        fanControlBetaShow: "Показывать управление вентиляторами (Бета) в панели",
        fanControlBetaSection: "Управление вентиляторами",
        fanControlBetaTitle: "Управление вентиляторами",
        fanControlBetaStatus: "Автоматически",
        fanControlBetaCaption: "Бета. Ручное управление отключено, пока не проверена каждая модель Mac.",
        fanControlModeAutomatic: "Автоматически",
        fanControlModeManual: "Вручную",
        betaBadge: "БЕТА",
        betaFeatureWarning: "Бета. Возможны ошибки.",

        networkSection: "Сеть",
        networkDownload: "Загрузка",
        networkUpload: "Отдача",
        networkThisSession: "За сеанс",
        networkMeasuring: "Измерение…",

        diskSection: "Диски",
        diskUsed: "занято",
        diskFree: "свободно",
        diskInternal: "Внутренний",
        diskExternal: "Внешний",
        diskSelect: "Выбрать диск",
        diskRead: "Чтение",
        diskWrite: "Запись",
        diskSMARTStatus: "Статус",
        diskSMARTUnavailable: "SMART недоступен для этого диска",
        diskTotalRead: "Всего прочитано",
        diskTotalWritten: "Всего записано",
        diskTemperature: "Температура",
        diskHealth: "Состояние",
        diskPowerCycles: "Циклы включения",
        diskPowerOnHours: "Часы работы",
        diskUnsafeShutdowns: "Небезопасные отключения",
        diskMediaErrors: "Ошибки носителя",
        diskEject: "Извлечь",
        diskEjectAll: "Извлечь все",
        diskEjecting: "Извлечение…",
        diskReadyToRemove: "Можно отключать",
        diskEjectFailed: "Не удалось извлечь",
        diskProtectionCaption: "Извлекайте перед отключением.",
        diskNoExternal: "Нет внешнего диска, готового к извлечению.",
        diskOpenInFinder: "Открыть",
        diskStorageSettings: "Хранилище",
        diskNoDisks: "Подключённые диски не найдены.",

        powerSection: "Питание",
        powerSystem: "Система",
        powerAdapter: "Адаптер",
        powerBattery: "Батарея",
        powerCharging: "Зарядка",
        powerOnBattery: "От батареи",
        powerPluggedIn: "Подключено",
        powerUnavailable: "Метрики питания недоступны на этом Mac",
        powerAdapterMaxFormat: "макс. %@",
        monitorShowGPU: "ГП",
        monitorShowCPUTemperature: "Температура ЦП",
        monitorShowGPUTemperature: "Температура ГП",
        monitorShowBatteryTemperature: "Температура батареи",
        monitorGraphsSection: "Графики",
        monitorGraphsCaption: "Выберите, для каких метрик показывать график во времени.",

        updateBannerTitle: "Доступно обновление",
        updateBannerAction: "Обновить",
        obStepMenuBarTitle: "Метрики в строке меню",
        obStepMenuBarBody: "Выберите, что показывать рядом со значком. Превью выше обновляется вживую.",
        obStepMenuBarNote: "Новое: блоки «Сеть» и «Питание» и графики в панели. Всё это можно настроить позже в «Настройки › Монитор».",
        monitorMenuBarPresetLabel: "Стиль",
        menuBarPresetReadable: "Читаемый",
        menuBarPresetDense: "Плотный",
        monitorLabelStyleLabel: "Подписи",
        menuBarLabelStyleCompact: "Компактные",
        menuBarLabelStyleClassic: "Классические",
        monitorMemoryStyleLabel: "Показывать память как",
        monitorMemoryPressureDot: "Точка нагрузки",
        memoryStyleDot: "Точка",
        memoryStylePercent: "%",
        memoryStyleBoth: "Оба",

        systemUptime: "В работе",
        powerHealth: "Состояние батареи",
        powerCycles: "циклов",
        speedTestRun: "Тест скорости",
        speedTestAgain: "Повторить тест",
        speedTestLatency: "Задержка",
        speedTestTesting: "Тестирование…",
        speedTestFailed: "Тест не удался",

        monitorShowInPanel: "Показывать в панели",
        panelHideItem: "Скрыть из панели",
        panelShowItem: "Показывать в панели",
        panelHiddenItem: "Скрыто",
        monitorItemUptime: "Время работы",
        monitorItemNetSpeed: "Текущая скорость",
        monitorItemNetTotals: "Итоги за сеанс",
        monitorItemNetTest: "Тест скорости",
        monitorItemDiskUsage: "Использование диска",
        monitorItemDiskActivity: "Текущая активность",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Защита внешних дисков",
        monitorItemDiskTools: "Инструменты",
        monitorPanelConfigHint: "Откройте блок, чтобы выбрать, что он показывает.",
        monitorOrderSection: "Порядок разделов",
        monitorOrderHint: "Перетаскивайте, чтобы изменить порядок разделов панели, и используйте глаз, чтобы показать или скрыть каждый.",
        obStepPanelTitle: "Что в панели",
        obStepPanelBody: "Откройте каждый блок и выберите, что именно показывать при нажатии на значок.",
        obStepPanelNavigationTitle: "Панель по разделам",
        obStepPanelNavigationBody: "Теперь панель может показывать по одному разделу за раз, с навигацией внизу. Для этого обновления она включена, чтобы вы могли попробовать.",

        cleaningMenuItem: "Режим очистки",
        utilitiesSection: "Утилиты",
        quickControlsSection: "Управление",
        windowMaximizeName: "Разворачивать окна",
        windowMaximizeCaption: "Зелёная кнопка разворачивает окно без создания нового пространства.",
        windowMaximizeActiveNow: "Переопределение зелёной кнопки активно",
        windowMaximizeNeedsAccessibility: "Нужен Универсальный доступ для работы.",
        cleaningPanelCaption: "Блокирует клавиатуру, чтобы можно было безопасно её протереть.",
        cleaningOverlayTitle: "Клавиатура заблокирована для очистки",
        cleaningOverlaySubtitle: "Нажмите одну и ту же клавишу 5 раз, чтобы разблокировать",
        cleaningOverlayUnlock: "Разблокировать",
        cleaningOverlayMouseHint: "Мышь и трекпад продолжают работать",
        cleaningNeedsAxTitle: "Нужен Универсальный доступ",
        cleaningNeedsAxBody: "Чтобы безопасно заблокировать клавиатуру, Vorssaint нужно разрешение Универсального доступа. Выдайте его в Системных настройках и попробуйте снова.",

        tabSupport: "Поддержать",
        donateHeading: "Поддержать Vorssaint",
        donateMessage: "Каждый из моих публичных проектов был и всегда будет полностью бесплатным: без подписки, без рекламы. Только поддержка сообщества держит его на плаву. Если Vorssaint вам помогает, чашка кофе действительно имеет значение.",
        donateButton: "Купить мне кофе",
        donateThanks: "Спасибо, что вы здесь. 🖤",
        supportIntroTitle: "Vorssaint на 100% бесплатен и таким останется",
        supportIntroMessage: "Я продолжаю заботиться о приложении в свободное время. Если оно вам помогает, вы можете помочь мне просто: поделиться им, поставить звезду на GitHub или купить мне кофе. Это очень помогает продолжать его улучшать.",
        supportIntroStarButton: "Поставить звезду",
        supportIntroCoffeeButton: "Купить мне кофе",
        supportIntroLaterButton: "Не сейчас",
        showMenuBarIcon: "Показывать значок в строке меню",
        showMenuBarIconCaption: "Если значок Vorssaint пропал (macOS может скрывать значки строки меню, когда в ней заканчивается место — частое явление на Mac с вырезом), откройте Vorssaint заново из «Программ» или Spotlight: это пересоздаст значок и, если он всё ещё скрыт, откроет это окно. Кнопка выше делает то же самое, когда вы уже можете сюда попасть. Чем меньше значков в строке меню или метрик Vorssaint, тем менее вероятно это произойдёт.",
        shortcutRecording: "Нажмите новое сочетание",
        shortcutReset: "Сбросить",
        shortcutInvalid: "Используйте хотя бы Control, Option или Command с клавишей.",
        shortcutConflictFormat: "Это сочетание уже занято: %@.",
        shortcutUnavailable: "macOS отклонила это сочетание. Выберите другое.",
        shelfShortcutToggle: "Сочетание для полки",
        switcherUsageHintFormat: "Удерживайте %@ для навигации; отпустите, чтобы активировать окно. Shift или ← — назад; Q закрывает выбранное приложение; Esc отменяет."
    )
}
